FROM python:3.12-slim
WORKDIR /app
COPY requirements.min.versions.txt .
RUN pip install --no-cache-dir -r requirements.min.versions.txt
COPY . .
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]