FROM python:3.12-slim
WORKDIR /app
COPY requirements.min.versions.txt .
RUN pip install --no-cache-dir -r requirements.min.versions.txt
COPY . .
CMD ["streamlit", "run", "app/ui.py", "--server.port", "8501", "--server.address", "0.0.0.0"]