services:
  api_gateway:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: phishing_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
  
  ui_dashboard:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: phishing_ui
    ports:
      - "8501:8501"
    environment:
      - API_ENDPOINT_URL=http://api_gateway:8000/api/v1/predict
    depends_on:
      - api_gateway
    volumes:
      - .:/app
